name: ~test template

on:
  workflow_call:
    inputs:
      RUNNER:
        type: string
        description: Runner to use for test
        required: true
      TIMEOUT:
        type: number
        description: Max runtime of test in minutes
        required: false
        default: 10
      SCRIPT:
        type: string
        description: Test script to execute
        required: true
      AFTER_SCRIPT:
        type: string
        description: Script to run after main test
        required: false
        default: ":"
      IS_OPTIONAL:
        type: boolean
        description: Failure will cancel all other tests if set to true
        required: false
        default: false
    outputs:
      conclusion:
        description: Conclusion of main test step
        value: ${{ jobs.main.outputs.conclusion }}
      log:
        description: Last 2000 characters of the test step's log
        value: ${{ jobs.main.outputs.log }} 
      potential_infra_failure:
        description: Boolean flag when infra-related keyword spotted in logs.
        value: ${{ jobs.main.outputs.potential_infra_failure }}
jobs:
  
  main:
    runs-on: ${{ inputs.RUNNER }} 
    outputs:
      conclusion: ${{ steps.main.conclusion }}
      log: ${{ steps.main.outputs.log }}
      potential_infra_failure: ${{ steps.main.outputs.potential_infra_failure }}
    env:
      CONTAINER_IMAGE: nemoci.azurecr.io/nemo_container:${{ github.run_id }}
      CONTAINER_NAME: $CONTAINER_NAME_${{ github.run_id }}_${{ github.run_attempt }}
    steps:
        - name: Docker system cleanup
          run: |
            docker system prune -a --filter "until=48h" --force || true

        - name: Docker pull image
          run: |
            docker pull nemoci.azurecr.io/nemo_container:${{ github.run_id }}

        - name: Stop all historic containers
          run: |
            docker ps --format '{{.Names}}' | grep -v "${CONTAINER_NAME}" | xargs -I{} docker container stop {}

        - name: Start container
          
          run: |
            ARG=("")
            if [[ "${{ inputs.RUNNER }}" != *cpu* ]]; then
              ARG=("--runtime=nvidia --gpus all")
            fi

            if docker ps --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then     
              echo Container $CONTAINER_NAME already running.
            else
              docker run --rm -d --name $CONTAINER_NAME ${ARG[@]} --shm-size=64g --env TRANSFORMERS_OFFLINE=0 --env HYDRA_FULL_ERROR=1 --volume /mnt/datadrive/TestData:/home/TestData $CONTAINER_IMAGE bash -c "sleep $(( 60 * 60 * 24 * 7 ))" || true
            fi            

        - id: main
          name: Run main script
          timeout-minutes: ${{ inputs.TIMEOUT }}
          run: |
            mkdir -p ${{ github.run_id }}
            cd ${{ github.run_id }}/
            set +e 
            (  
              set -e

              docker exec $CONTAINER_NAME bash -c '${{ inputs.SCRIPT }}'
            ) 2> >(tee err.log)

            EXIT_CODE=$?
            
            echo "log=$(tail -c 2000 err.log |  base64 -w 0)" >> "$GITHUB_OUTPUT"
            
            potential_infra_failure=$(cat err.log | grep -Eqiw "device" && echo true || echo false)
            echo "potential_infra_failure=$potential_infra_failure" >> "$GITHUB_OUTPUT"

            exit $EXIT_CODE
            
        - uses: "NVIDIA/NeMo/.github/actions/cancel-workflow@main"
          if: failure() && inputs.IS_OPTIONAL == false
        - name: after_script
          if: always() && inputs.AFTER_SCRIPT != ':'
          run: |
            docker exec $CONTAINER_NAME bash -c '${{ inputs.AFTER_SCRIPT }}'
